### PR TITLE
Add nodes for OpenDoorsWindows and UserDefinedStates

### PR DESCRIPTION
**Pull request by saemmy**
Add 2 new nodes

- Get OpenDoorsWindows
- Get/Set UserDefinedStates

### CODE REVIEW

**Comment by saemmy** [comment]
Hi @hxmelab , I tested this locally, works fine, but there is one point: when setting a UserDefinedState, I get two responses: the first one is the longpolling-event containing the old value and the second one is the msg.payload with the correct new value. Is there any possibility to suppress the first message with the old value?

**Comment by hxmelab** [comment]
Hi Saemmy, thanks for you contribution. To answer your question, I need some more context. What's the goal of the new nodes you provide? Why does the current nodes does not fulfill your needs, etc.

**Comment by saemmy** [comment]
OpenDoorsWindows node is fine.
Wth the UserDefinedState node, you can reproduce it the following way:
* create a new UserDefined state in your Bosch SmartHomeSystem (Automations/Szenario tab)
* Add node and select the before created state
* put <true> in the node
* you will receive one event with status <false> that´s from the longpolling
* you will receive a second message with status <true>
I would like to suppress the first longpolling event.

**Comment by saemmy** [comment]
May be I got it. It´s because when I´d like to set a state I do a PUT and a GET afterwards. If I just do a PUT, there is only one message. I will commit a fix...

**Pull request closed without merging**
